/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2026-03-30 12:55:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.dao.UserDAO;
import com.dao.LogDAO;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/sidebar.jsp", Long.valueOf(1774874789771L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.dao.UserDAO");
    _jspx_imports_classes.add("com.dao.LogDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Dashboard - Secure Password Manager</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");

        // Session data (guaranteed by SessionFilter)
        int userId = (int) session.getAttribute("userId");
        String username = (String) session.getAttribute("username");
        String email = (String) session.getAttribute("email");
        
        // Fetch dashboard stats
        UserDAO userDAO = new UserDAO();
        LogDAO logDAO = new LogDAO();
        int passwordCount = userDAO.getPasswordCount(userId);
        String lastLogin = logDAO.getLastLoginTime(userId);
    
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"dashboard-layout\">\n");
      out.write("        <!-- ==================== Sidebar ==================== -->\n");
      out.write("        ");
      out.write('\n');
      out.write('\n');

    // Get current page for active state highlighting
    String currentPage = request.getRequestURI();
    String ctx = request.getContextPath();
    String sidebarUsername = (String) session.getAttribute("username");
    if (sidebarUsername == null) sidebarUsername = "User";

      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"sidebar\">\n");
      out.write("    <!-- Logo -->\n");
      out.write("    <div class=\"sidebar-logo\">\n");
      out.write("        <div class=\"logo-icon\">&#128274;</div>\n");
      out.write("        <h2>SecureVault</h2>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Navigation Links -->\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/dashboard.jsp\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("dashboard") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#127968; Dashboard\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/VaultServlet?action=list\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("viewPasswords") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#128273; My Passwords\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/VaultServlet?action=add\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("addPassword") || currentPage.contains("editPassword") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#10133; Add Password\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/LogsServlet\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("logs") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#128203; Activity Logs\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("    <!-- User Section -->\n");
      out.write("    <div class=\"sidebar-user\">\n");
      out.write("        <div class=\"user-info\">\n");
      out.write("            <div class=\"user-avatar\">");
      out.print( sidebarUsername.substring(0, 1).toUpperCase() );
      out.write("</div>\n");
      out.write("            <span>");
      out.print( sidebarUsername.replace("<", "&lt;") );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"");
      out.print( ctx );
      out.write("/LogoutServlet\" class=\"btn-logout\">\n");
      out.write("            &#128682; Sign Out\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        <!-- ==================== Main Content ==================== -->\n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"page-header\">\n");
      out.write("                <h1>Dashboard</h1>\n");
      out.write("                <span class=\"text-sm text-muted\">Welcome back, <strong>");
      out.print( username.replace("<", "&lt;") );
      out.write("</strong></span>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Stats Cards -->\n");
      out.write("            <div class=\"stats-grid\">\n");
      out.write("                <div class=\"stat-card accent\">\n");
      out.write("                    <div class=\"stat-label\">Stored Passwords</div>\n");
      out.write("                    <div class=\"stat-value\">");
      out.print( passwordCount );
      out.write("</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"stat-card success\">\n");
      out.write("                    <div class=\"stat-label\">Last Login</div>\n");
      out.write("                    <div class=\"stat-value\" style=\"font-size:16px;\">");
      out.print( lastLogin.replace("<", "&lt;") );
      out.write("</div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"stat-card warning\">\n");
      out.write("                    <div class=\"stat-label\">Session Timeout</div>\n");
      out.write("                    <div class=\"stat-value\" id=\"sessionTimer\">5:00</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Quick Actions -->\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h3>Quick Actions</h3>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"btn-group\" style=\"flex-wrap:wrap; gap:12px;\">\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VaultServlet?action=add\" class=\"btn btn-primary\">\n");
      out.write("                        &#43; Add New Password\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VaultServlet?action=list\" class=\"btn btn-secondary\">\n");
      out.write("                        &#128270; View All Passwords\n");
      out.write("                    </a>\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogsServlet\" class=\"btn btn-secondary\">\n");
      out.write("                        &#128203; Activity Logs\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <!-- Security Info -->\n");
      out.write("            <div class=\"card\">\n");
      out.write("                <div class=\"card-header\">\n");
      out.write("                    <h3>Security Information</h3>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"alert alert-info\" style=\"margin-bottom:8px;\">\n");
      out.write("                    &#128274; Your passwords are encrypted with AES using a key derived from your login password. \n");
      out.write("                    Only you can decrypt them.\n");
      out.write("                </div>\n");
      out.write("                <div class=\"alert alert-warning\" style=\"margin-bottom:0;\">\n");
      out.write("                    &#9200; Your session will expire after 5 minutes of inactivity. \n");
      out.write("                    You will need to log in again.\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        // Session countdown timer (5 minutes = 300 seconds)\n");
      out.write("        var timeLeft = 300;\n");
      out.write("        var timerDisplay = document.getElementById('sessionTimer');\n");
      out.write("        \n");
      out.write("        var countdown = setInterval(function() {\n");
      out.write("            timeLeft--;\n");
      out.write("            var minutes = Math.floor(timeLeft / 60);\n");
      out.write("            var seconds = timeLeft % 60;\n");
      out.write("            timerDisplay.textContent = minutes + ':' + (seconds < 10 ? '0' : '') + seconds;\n");
      out.write("            \n");
      out.write("            if (timeLeft <= 60) {\n");
      out.write("                timerDisplay.style.color = 'var(--danger)';\n");
      out.write("            } else if (timeLeft <= 120) {\n");
      out.write("                timerDisplay.style.color = 'var(--warning)';\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            if (timeLeft <= 0) {\n");
      out.write("                clearInterval(countdown);\n");
      out.write("                alert('Session expired! You will be redirected to login.');\n");
      out.write("                window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp?error=session_expired';\n");
      out.write("            }\n");
      out.write("        }, 1000);\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
