/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2026-03-30 12:57:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.Vault;

public final class editPassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/sidebar.jsp", Long.valueOf(1774874789771L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.model.Vault");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Edit Password - Secure Password Manager</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");

        Vault vault = (Vault) request.getAttribute("vault");
        if (vault == null) {
            response.sendRedirect(request.getContextPath() + "/VaultServlet?action=list");
            return;
        }
    
      out.write("\n");
      out.write("    \n");
      out.write("    <div class=\"dashboard-layout\">\n");
      out.write("        ");
      out.write('\n');
      out.write('\n');

    // Get current page for active state highlighting
    String currentPage = request.getRequestURI();
    String ctx = request.getContextPath();
    String sidebarUsername = (String) session.getAttribute("username");
    if (sidebarUsername == null) sidebarUsername = "User";

      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"sidebar\">\n");
      out.write("    <!-- Logo -->\n");
      out.write("    <div class=\"sidebar-logo\">\n");
      out.write("        <div class=\"logo-icon\">&#128274;</div>\n");
      out.write("        <h2>SecureVault</h2>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Navigation Links -->\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/dashboard.jsp\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("dashboard") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#127968; Dashboard\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/VaultServlet?action=list\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("viewPasswords") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#128273; My Passwords\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/VaultServlet?action=add\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("addPassword") || currentPage.contains("editPassword") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#10133; Add Password\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/LogsServlet\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("logs") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#128203; Activity Logs\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("    <!-- User Section -->\n");
      out.write("    <div class=\"sidebar-user\">\n");
      out.write("        <div class=\"user-info\">\n");
      out.write("            <div class=\"user-avatar\">");
      out.print( sidebarUsername.substring(0, 1).toUpperCase() );
      out.write("</div>\n");
      out.write("            <span>");
      out.print( sidebarUsername.replace("<", "&lt;") );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"");
      out.print( ctx );
      out.write("/LogoutServlet\" class=\"btn-logout\">\n");
      out.write("            &#128682; Sign Out\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"page-header\">\n");
      out.write("                <h1>Edit Credential</h1>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VaultServlet?action=list\" class=\"btn btn-secondary\">\n");
      out.write("                    &larr; Back to Vault\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
 String error = (String) request.getAttribute("error"); 
      out.write("\n");
      out.write("            ");
 if (error != null) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-error\">\n");
      out.write("                    &#9888; ");
      out.print( error.replace("<", "&lt;").replace(">", "&gt;") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <div class=\"card\">\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VaultServlet\" method=\"POST\">\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"update\">\n");
      out.write("                    <input type=\"hidden\" name=\"id\" value=\"");
      out.print( vault.getId() );
      out.write("\">\n");
      out.write("                    \n");
      out.write("                    ");
      out.write("\n");
      out.write("                    ");
 
                        String csrfToken = (String) request.getAttribute("csrfToken");
                        if (csrfToken == null) csrfToken = com.util.CSRFUtil.getToken(session);
                    
      out.write("\n");
      out.write("                    <input type=\"hidden\" name=\"csrfToken\" value=\"");
      out.print( csrfToken );
      out.write("\">\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"website\">Website / Service</label>\n");
      out.write("                        <input type=\"text\" id=\"website\" name=\"website\" class=\"form-control\" \n");
      out.write("                               value=\"");
      out.print( vault.getWebsite().replace("\"", "&quot;").replace("<", "&lt;") );
      out.write("\" required>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"siteUsername\">Username / Email</label>\n");
      out.write("                        <input type=\"text\" id=\"siteUsername\" name=\"siteUsername\" class=\"form-control\" \n");
      out.write("                               value=\"");
      out.print( vault.getSiteUsername().replace("\"", "&quot;").replace("<", "&lt;") );
      out.write("\" required>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                        <label for=\"sitePassword\">Password</label>\n");
      out.write("                        <div class=\"password-field\">\n");
      out.write("                            <input type=\"password\" id=\"sitePassword\" name=\"sitePassword\" class=\"form-control\" \n");
      out.write("                                   value=\"");
      out.print( vault.getDecryptedPassword() != null ? vault.getDecryptedPassword().replace("\"", "&quot;").replace("<", "&lt;") : "" );
      out.write("\" \n");
      out.write("                                   required onkeyup=\"checkStrength()\">\n");
      out.write("                            <button type=\"button\" class=\"btn-icon\" onclick=\"togglePassword('sitePassword', this)\">&#128065;</button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"strength-bar-container\" id=\"strengthBarContainer\" style=\"display:none;\">\n");
      out.write("                            <div class=\"strength-bar\" id=\"strengthBar\"></div>\n");
      out.write("                        </div>\n");
      out.write("                        <span class=\"strength-indicator\" id=\"strengthLabel\" style=\"display:none;margin-top:6px;\"></span>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <!-- Password Generator -->\n");
      out.write("                    <div class=\"generator-section\">\n");
      out.write("                        <h4>&#9889; Password Generator</h4>\n");
      out.write("                        <div class=\"generator-controls\">\n");
      out.write("                            <label for=\"genLength\">Length:</label>\n");
      out.write("                            <select id=\"genLength\" class=\"form-control\" style=\"width:auto;\">\n");
      out.write("                                <option value=\"8\">8</option>\n");
      out.write("                                <option value=\"10\">10</option>\n");
      out.write("                                <option value=\"12\" selected>12</option>\n");
      out.write("                                <option value=\"14\">14</option>\n");
      out.write("                                <option value=\"16\">16</option>\n");
      out.write("                            </select>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-success btn-sm\" onclick=\"generatePassword()\">\n");
      out.write("                                Generate Strong Password\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary btn-block\" style=\"margin-top:20px;\">\n");
      out.write("                        &#128190; Update Credential\n");
      out.write("                    </button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        function togglePassword(fieldId, btn) {\n");
      out.write("            var field = document.getElementById(fieldId);\n");
      out.write("            if (field.type === 'password') {\n");
      out.write("                field.type = 'text';\n");
      out.write("                btn.innerHTML = '&#128064;';\n");
      out.write("            } else {\n");
      out.write("                field.type = 'password';\n");
      out.write("                btn.innerHTML = '&#128065;';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function generatePassword() {\n");
      out.write("            var length = document.getElementById('genLength').value;\n");
      out.write("            var xhr = new XMLHttpRequest();\n");
      out.write("            xhr.open('GET', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VaultServlet?action=generate&length=' + length, true);\n");
      out.write("            xhr.onreadystatechange = function() {\n");
      out.write("                if (xhr.readyState === 4 && xhr.status === 200) {\n");
      out.write("                    var passwordField = document.getElementById('sitePassword');\n");
      out.write("                    passwordField.value = xhr.responseText;\n");
      out.write("                    passwordField.type = 'text';\n");
      out.write("                    checkStrength();\n");
      out.write("                }\n");
      out.write("            };\n");
      out.write("            xhr.send();\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function checkStrength() {\n");
      out.write("            var password = document.getElementById('sitePassword').value;\n");
      out.write("            var bar = document.getElementById('strengthBar');\n");
      out.write("            var label = document.getElementById('strengthLabel');\n");
      out.write("            var container = document.getElementById('strengthBarContainer');\n");
      out.write("            \n");
      out.write("            if (password.length === 0) {\n");
      out.write("                container.style.display = 'none';\n");
      out.write("                label.style.display = 'none';\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            container.style.display = 'block';\n");
      out.write("            label.style.display = 'inline-block';\n");
      out.write("            \n");
      out.write("            var score = 0;\n");
      out.write("            if (password.length >= 8) score++;\n");
      out.write("            if (/[A-Z]/.test(password)) score++;\n");
      out.write("            if (/[a-z]/.test(password)) score++;\n");
      out.write("            if (/[0-9]/.test(password)) score++;\n");
      out.write("            if (/[^A-Za-z0-9]/.test(password)) score++;\n");
      out.write("            \n");
      out.write("            if (score <= 2) {\n");
      out.write("                bar.className = 'strength-bar weak';\n");
      out.write("                label.className = 'strength-indicator strength-weak';\n");
      out.write("                label.textContent = 'Weak';\n");
      out.write("            } else if (score <= 4) {\n");
      out.write("                bar.className = 'strength-bar medium';\n");
      out.write("                label.className = 'strength-indicator strength-medium';\n");
      out.write("                label.textContent = 'Medium';\n");
      out.write("            } else {\n");
      out.write("                bar.className = 'strength-bar strong';\n");
      out.write("                label.className = 'strength-indicator strength-strong';\n");
      out.write("                label.textContent = 'Strong';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
