/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2026-03-30 12:57:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.model.Log;

public final class logs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/sidebar.jsp", Long.valueOf(1774874789771L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.Log");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Activity Logs - Secure Password Manager</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-layout\">\n");
      out.write("        ");
      out.write('\n');
      out.write('\n');

    // Get current page for active state highlighting
    String currentPage = request.getRequestURI();
    String ctx = request.getContextPath();
    String sidebarUsername = (String) session.getAttribute("username");
    if (sidebarUsername == null) sidebarUsername = "User";

      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"sidebar\">\n");
      out.write("    <!-- Logo -->\n");
      out.write("    <div class=\"sidebar-logo\">\n");
      out.write("        <div class=\"logo-icon\">&#128274;</div>\n");
      out.write("        <h2>SecureVault</h2>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Navigation Links -->\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/dashboard.jsp\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("dashboard") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#127968; Dashboard\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/VaultServlet?action=list\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("viewPasswords") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#128273; My Passwords\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/VaultServlet?action=add\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("addPassword") || currentPage.contains("editPassword") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#10133; Add Password\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/LogsServlet\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("logs") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#128203; Activity Logs\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("    <!-- User Section -->\n");
      out.write("    <div class=\"sidebar-user\">\n");
      out.write("        <div class=\"user-info\">\n");
      out.write("            <div class=\"user-avatar\">");
      out.print( sidebarUsername.substring(0, 1).toUpperCase() );
      out.write("</div>\n");
      out.write("            <span>");
      out.print( sidebarUsername.replace("<", "&lt;") );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"");
      out.print( ctx );
      out.write("/LogoutServlet\" class=\"btn-logout\">\n");
      out.write("            &#128682; Sign Out\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"page-header\">\n");
      out.write("                <h1>Activity Logs</h1>\n");
      out.write("                <span class=\"text-sm text-muted\">Last 50 actions</span>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");

                List<Log> logs = (List<Log>) request.getAttribute("logs");
            
      out.write("\n");
      out.write("            \n");
      out.write("            ");
 if (logs != null && !logs.isEmpty()) { 
      out.write("\n");
      out.write("                <div class=\"card\" style=\"padding:0;\">\n");
      out.write("                    <div class=\"table-container\">\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>#</th>\n");
      out.write("                                    <th>Action</th>\n");
      out.write("                                    <th>IP Address</th>\n");
      out.write("                                    <th>Timestamp</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                ");
 int index = 1; 
      out.write("\n");
      out.write("                                ");
 for (Log log : logs) { 
                                    String action = log.getAction();
                                    String actionClass = "registration";
                                    String icon = "&#128204;";
                                    
                                    if (action.contains("LOGIN_SUCCESS")) {
                                        actionClass = "login-success"; icon = "&#9989;";
                                    } else if (action.contains("LOGIN_FAILED")) {
                                        actionClass = "login-failed"; icon = "&#10060;";
                                    } else if (action.contains("LOGIN_LOCKED")) {
                                        actionClass = "login-locked"; icon = "&#128274;";
                                    } else if (action.contains("LOGOUT")) {
                                        actionClass = "logout"; icon = "&#128682;";
                                    } else if (action.contains("PASSWORD_ADDED")) {
                                        actionClass = "password-added"; icon = "&#10133;";
                                    } else if (action.contains("PASSWORD_UPDATED")) {
                                        actionClass = "password-updated"; icon = "&#9998;";
                                    } else if (action.contains("PASSWORD_DELETED")) {
                                        actionClass = "password-deleted"; icon = "&#128465;";
                                    } else if (action.contains("REGISTRATION")) {
                                        actionClass = "registration"; icon = "&#127881;";
                                    }
                                
      out.write("\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td class=\"text-muted\">");
      out.print( index++ );
      out.write("</td>\n");
      out.write("                                        <td>\n");
      out.write("                                            <span class=\"log-action ");
      out.print( actionClass );
      out.write("\">\n");
      out.write("                                                <span class=\"log-icon\">");
      out.print( icon );
      out.write("</span>\n");
      out.write("                                                ");
      out.print( action.replace("<", "&lt;").replace(">", "&gt;") );
      out.write("\n");
      out.write("                                            </span>\n");
      out.write("                                        </td>\n");
      out.write("                                        <td>\n");
      out.write("                                            <code style=\"font-size:13px; color:var(--text-secondary);\">\n");
      out.write("                                                ");
      out.print( log.getIpAddress() != null ? log.getIpAddress().replace("<", "&lt;") : "N/A" );
      out.write("\n");
      out.write("                                            </code>\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"text-sm text-muted\">\n");
      out.write("                                            ");
      out.print( log.getTimestamp() != null ? log.getTimestamp().toString().substring(0, 19) : "N/A" );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <p class=\"text-sm text-muted text-center\">\n");
      out.write("                    Showing ");
      out.print( logs.size() );
      out.write(" log entries. All actions are permanently recorded.\n");
      out.write("                </p>\n");
      out.write("                \n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <div class=\"empty-state\">\n");
      out.write("                        <div class=\"empty-icon\">&#128203;</div>\n");
      out.write("                        <h3>No Activity Logged Yet</h3>\n");
      out.write("                        <p>Your actions will appear here as you use the password manager.</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
