/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2026-03-30 12:53:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name=\"description\" content=\"Create your Secure Password Manager account\">\n");
      out.write("    <title>Register - Secure Password Manager</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"auth-container\">\n");
      out.write("        <div class=\"auth-card\">\n");
      out.write("            <!-- Logo Section -->\n");
      out.write("            <div class=\"logo-section\">\n");
      out.write("                <div class=\"shield-icon\">&#128274;</div>\n");
      out.write("                <h1>Create Account</h1>\n");
      out.write("                <p class=\"subtitle\">Start securing your passwords today</p>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
 String error = (String) request.getAttribute("error"); 
      out.write("\n");
      out.write("            ");
 if (error != null && !error.isEmpty()) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-error\">\n");
      out.write("                    &#9888; ");
      out.print( error.replace("<", "&lt;").replace(">", "&gt;") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <!-- Registration Form -->\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/RegisterServlet\" method=\"POST\" id=\"registerForm\">\n");
      out.write("                ");
      out.write("\n");
      out.write("                ");
 
                    String csrfToken = (String) request.getAttribute("csrfToken");
                    if (csrfToken == null) {
                        csrfToken = com.util.CSRFUtil.getToken(session);
                    }
                
      out.write("\n");
      out.write("                <input type=\"hidden\" name=\"csrfToken\" value=\"");
      out.print( csrfToken );
      out.write("\">\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"username\">Username</label>\n");
      out.write("                    <input type=\"text\" id=\"username\" name=\"username\" class=\"form-control\" \n");
      out.write("                           placeholder=\"Letters, numbers, underscore (3-50 chars)\" required\n");
      out.write("                           pattern=\"^[a-zA-Z0-9_]{3,50}$\" autocomplete=\"username\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"email\">Email Address</label>\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\" \n");
      out.write("                           placeholder=\"you@example.com\" required autocomplete=\"email\">\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"password\">Password</label>\n");
      out.write("                    <div class=\"password-field\">\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"password\" class=\"form-control\" \n");
      out.write("                               placeholder=\"Min 8 characters, mixed case & symbols\" required \n");
      out.write("                               minlength=\"8\" onkeyup=\"checkPasswordStrength()\"\n");
      out.write("                               autocomplete=\"new-password\">\n");
      out.write("                        <button type=\"button\" class=\"btn-icon\" onclick=\"togglePassword('password', this)\">&#128065;</button>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Password strength indicator -->\n");
      out.write("                    <div class=\"strength-bar-container\" id=\"strengthBarContainer\" style=\"display:none;\">\n");
      out.write("                        <div class=\"strength-bar\" id=\"strengthBar\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"strength-indicator\" id=\"strengthLabel\" style=\"display:none;\"></span>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                    <label for=\"confirmPassword\">Confirm Password</label>\n");
      out.write("                    <div class=\"password-field\">\n");
      out.write("                        <input type=\"password\" id=\"confirmPassword\" name=\"confirmPassword\" class=\"form-control\" \n");
      out.write("                               placeholder=\"Re-enter your password\" required autocomplete=\"new-password\">\n");
      out.write("                        <button type=\"button\" class=\"btn-icon\" onclick=\"togglePassword('confirmPassword', this)\">&#128065;</button>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"text-sm text-muted\" id=\"matchMessage\" style=\"margin-top:4px;display:none;\"></span>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary btn-block\" style=\"margin-top: 8px;\">\n");
      out.write("                    Create Account\n");
      out.write("                </button>\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("            <div class=\"auth-footer\">\n");
      out.write("                Already have an account? \n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LoginServlet\">Sign in</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        // Toggle password visibility\n");
      out.write("        function togglePassword(fieldId, btn) {\n");
      out.write("            var field = document.getElementById(fieldId);\n");
      out.write("            if (field.type === 'password') {\n");
      out.write("                field.type = 'text';\n");
      out.write("                btn.innerHTML = '&#128064;';\n");
      out.write("            } else {\n");
      out.write("                field.type = 'password';\n");
      out.write("                btn.innerHTML = '&#128065;';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Client-side password strength checker\n");
      out.write("        function checkPasswordStrength() {\n");
      out.write("            var password = document.getElementById('password').value;\n");
      out.write("            var bar = document.getElementById('strengthBar');\n");
      out.write("            var label = document.getElementById('strengthLabel');\n");
      out.write("            var container = document.getElementById('strengthBarContainer');\n");
      out.write("            \n");
      out.write("            if (password.length === 0) {\n");
      out.write("                container.style.display = 'none';\n");
      out.write("                label.style.display = 'none';\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            container.style.display = 'block';\n");
      out.write("            label.style.display = 'inline-block';\n");
      out.write("            label.style.marginTop = '6px';\n");
      out.write("            \n");
      out.write("            var score = 0;\n");
      out.write("            if (password.length >= 8) score++;\n");
      out.write("            if (/[A-Z]/.test(password)) score++;\n");
      out.write("            if (/[a-z]/.test(password)) score++;\n");
      out.write("            if (/[0-9]/.test(password)) score++;\n");
      out.write("            if (/[^A-Za-z0-9]/.test(password)) score++;\n");
      out.write("            \n");
      out.write("            if (score <= 2) {\n");
      out.write("                bar.className = 'strength-bar weak';\n");
      out.write("                label.className = 'strength-indicator strength-weak';\n");
      out.write("                label.textContent = 'Weak';\n");
      out.write("            } else if (score <= 4) {\n");
      out.write("                bar.className = 'strength-bar medium';\n");
      out.write("                label.className = 'strength-indicator strength-medium';\n");
      out.write("                label.textContent = 'Medium';\n");
      out.write("            } else {\n");
      out.write("                bar.className = 'strength-bar strong';\n");
      out.write("                label.className = 'strength-indicator strength-strong';\n");
      out.write("                label.textContent = 'Strong';\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            checkPasswordMatch();\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Check if passwords match\n");
      out.write("        function checkPasswordMatch() {\n");
      out.write("            var password = document.getElementById('password').value;\n");
      out.write("            var confirm = document.getElementById('confirmPassword').value;\n");
      out.write("            var msg = document.getElementById('matchMessage');\n");
      out.write("            \n");
      out.write("            if (confirm.length === 0) {\n");
      out.write("                msg.style.display = 'none';\n");
      out.write("                return;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            msg.style.display = 'block';\n");
      out.write("            if (password === confirm) {\n");
      out.write("                msg.textContent = '✓ Passwords match';\n");
      out.write("                msg.style.color = 'var(--success)';\n");
      out.write("            } else {\n");
      out.write("                msg.textContent = '✗ Passwords do not match';\n");
      out.write("                msg.style.color = 'var(--danger)';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        document.getElementById('confirmPassword').addEventListener('keyup', checkPasswordMatch);\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
