/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.113
 * Generated at: 2026-03-30 12:55:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.model.Vault;

public final class viewPasswords_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/sidebar.jsp", Long.valueOf(1774874789771L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.Vault");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>My Passwords - Secure Password Manager</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"dashboard-layout\">\n");
      out.write("        ");
      out.write('\n');
      out.write('\n');

    // Get current page for active state highlighting
    String currentPage = request.getRequestURI();
    String ctx = request.getContextPath();
    String sidebarUsername = (String) session.getAttribute("username");
    if (sidebarUsername == null) sidebarUsername = "User";

      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"sidebar\">\n");
      out.write("    <!-- Logo -->\n");
      out.write("    <div class=\"sidebar-logo\">\n");
      out.write("        <div class=\"logo-icon\">&#128274;</div>\n");
      out.write("        <h2>SecureVault</h2>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- Navigation Links -->\n");
      out.write("    <ul class=\"sidebar-nav\">\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/dashboard.jsp\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("dashboard") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#127968; Dashboard\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/VaultServlet?action=list\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("viewPasswords") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#128273; My Passwords\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/VaultServlet?action=add\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("addPassword") || currentPage.contains("editPassword") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#10133; Add Password\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("        <li>\n");
      out.write("            <a href=\"");
      out.print( ctx );
      out.write("/LogsServlet\" \n");
      out.write("               class=\"");
      out.print( currentPage.contains("logs") ? "active" : "" );
      out.write("\">\n");
      out.write("                &#128203; Activity Logs\n");
      out.write("            </a>\n");
      out.write("        </li>\n");
      out.write("    </ul>\n");
      out.write("    \n");
      out.write("    <!-- User Section -->\n");
      out.write("    <div class=\"sidebar-user\">\n");
      out.write("        <div class=\"user-info\">\n");
      out.write("            <div class=\"user-avatar\">");
      out.print( sidebarUsername.substring(0, 1).toUpperCase() );
      out.write("</div>\n");
      out.write("            <span>");
      out.print( sidebarUsername.replace("<", "&lt;") );
      out.write("</span>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"");
      out.print( ctx );
      out.write("/LogoutServlet\" class=\"btn-logout\">\n");
      out.write("            &#128682; Sign Out\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"main-content\">\n");
      out.write("            <div class=\"page-header\">\n");
      out.write("                <h1>My Passwords</h1>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VaultServlet?action=add\" class=\"btn btn-primary\">\n");
      out.write("                    &#43; Add New\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
 String success = request.getParameter("success"); 
      out.write("\n");
      out.write("            ");
 if (success != null && !success.isEmpty()) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-success\">\n");
      out.write("                    &#10004; ");
      out.print( success.replace("<", "&lt;").replace(">", "&gt;") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            ");
      out.write("\n");
      out.write("            ");
 
                String error = (String) request.getAttribute("error");
                if (error == null) error = request.getParameter("error");
            
      out.write("\n");
      out.write("            ");
 if (error != null && !error.isEmpty()) { 
      out.write("\n");
      out.write("                <div class=\"alert alert-error\">\n");
      out.write("                    &#9888; ");
      out.print( error.replace("<", "&lt;").replace(">", "&gt;") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            ");

                List<Vault> credentials = (List<Vault>) request.getAttribute("credentials");
            
      out.write("\n");
      out.write("            \n");
      out.write("            ");
 if (credentials != null && !credentials.isEmpty()) { 
      out.write("\n");
      out.write("                <div class=\"card\" style=\"padding:0;\">\n");
      out.write("                    <div class=\"table-container\">\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>#</th>\n");
      out.write("                                    <th>Website</th>\n");
      out.write("                                    <th>Username</th>\n");
      out.write("                                    <th>Password</th>\n");
      out.write("                                    <th>Added On</th>\n");
      out.write("                                    <th>Actions</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                ");
 int index = 1; 
      out.write("\n");
      out.write("                                ");
 for (Vault v : credentials) { 
      out.write("\n");
      out.write("                                    <tr>\n");
      out.write("                                        <td>");
      out.print( index++ );
      out.write("</td>\n");
      out.write("                                        <td><strong>");
      out.print( v.getWebsite().replace("<", "&lt;").replace(">", "&gt;") );
      out.write("</strong></td>\n");
      out.write("                                        <td>");
      out.print( v.getSiteUsername().replace("<", "&lt;").replace(">", "&gt;") );
      out.write("</td>\n");
      out.write("                                        <td>\n");
      out.write("                                            <div class=\"password-display\">\n");
      out.write("                                                <span class=\"password-mask\" id=\"pwd-mask-");
      out.print( v.getId() );
      out.write("\">••••••••</span>\n");
      out.write("                                                <span style=\"display:none;\" id=\"pwd-text-");
      out.print( v.getId() );
      out.write('"');
      out.write('>');
      out.print( v.getDecryptedPassword() != null ? v.getDecryptedPassword().replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;") : "" );
      out.write("</span>\n");
      out.write("                                                <button class=\"btn-copy\" onclick=\"toggleVaultPwd(");
      out.print( v.getId() );
      out.write(")\" title=\"Show/Hide\">&#128065;</button>\n");
      out.write("                                                <button class=\"btn-copy\" onclick=\"copyToClipboard(");
      out.print( v.getId() );
      out.write(")\" title=\"Copy\">&#128203;</button>\n");
      out.write("                                            </div>\n");
      out.write("                                        </td>\n");
      out.write("                                        <td class=\"text-sm text-muted\">\n");
      out.write("                                            ");
      out.print( v.getCreatedAt() != null ? v.getCreatedAt().toString().substring(0, 16) : "N/A" );
      out.write("\n");
      out.write("                                        </td>\n");
      out.write("                                        <td>\n");
      out.write("                                            <div class=\"btn-group\">\n");
      out.write("                                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VaultServlet?action=edit&id=");
      out.print( v.getId() );
      out.write("\" \n");
      out.write("                                                   class=\"btn btn-secondary btn-sm\">Edit</a>\n");
      out.write("                                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VaultServlet?action=delete&id=");
      out.print( v.getId() );
      out.write("\" \n");
      out.write("                                                   class=\"btn btn-danger btn-sm\"\n");
      out.write("                                                   onclick=\"return confirm('Delete this credential for ");
      out.print( v.getWebsite().replace("'", "\\'").replace("<", "&lt;") );
      out.write("? This cannot be undone.');\">Delete</a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </td>\n");
      out.write("                                    </tr>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <p class=\"text-sm text-muted text-center\">\n");
      out.write("                    Showing ");
      out.print( credentials.size() );
      out.write(" credential(s). Passwords are AES-encrypted at rest.\n");
      out.write("                </p>\n");
      out.write("                \n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <!-- Empty State -->\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <div class=\"empty-state\">\n");
      out.write("                        <div class=\"empty-icon\">&#128274;</div>\n");
      out.write("                        <h3>No Passwords Stored Yet</h3>\n");
      out.write("                        <p>Start by adding your first credential to the vault.</p>\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/VaultServlet?action=add\" class=\"btn btn-primary\">\n");
      out.write("                            &#43; Add Your First Password\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        // Toggle individual password visibility in the table\n");
      out.write("        function toggleVaultPwd(id) {\n");
      out.write("            var mask = document.getElementById('pwd-mask-' + id);\n");
      out.write("            var text = document.getElementById('pwd-text-' + id);\n");
      out.write("            \n");
      out.write("            if (mask.style.display !== 'none') {\n");
      out.write("                mask.style.display = 'none';\n");
      out.write("                text.style.display = 'inline';\n");
      out.write("            } else {\n");
      out.write("                mask.style.display = 'inline';\n");
      out.write("                text.style.display = 'none';\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        // Copy password to clipboard\n");
      out.write("        function copyToClipboard(id) {\n");
      out.write("            var text = document.getElementById('pwd-text-' + id).textContent;\n");
      out.write("            \n");
      out.write("            if (navigator.clipboard) {\n");
      out.write("                navigator.clipboard.writeText(text).then(function() {\n");
      out.write("                    showCopyNotification();\n");
      out.write("                });\n");
      out.write("            } else {\n");
      out.write("                // Fallback for older browsers\n");
      out.write("                var textarea = document.createElement('textarea');\n");
      out.write("                textarea.value = text;\n");
      out.write("                document.body.appendChild(textarea);\n");
      out.write("                textarea.select();\n");
      out.write("                document.execCommand('copy');\n");
      out.write("                document.body.removeChild(textarea);\n");
      out.write("                showCopyNotification();\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function showCopyNotification() {\n");
      out.write("            var notification = document.createElement('div');\n");
      out.write("            notification.className = 'alert alert-success';\n");
      out.write("            notification.style.position = 'fixed';\n");
      out.write("            notification.style.top = '20px';\n");
      out.write("            notification.style.right = '20px';\n");
      out.write("            notification.style.zIndex = '9999';\n");
      out.write("            notification.style.animation = 'fadeIn 0.3s ease-out';\n");
      out.write("            notification.innerHTML = '&#10004; Password copied to clipboard!';\n");
      out.write("            document.body.appendChild(notification);\n");
      out.write("            \n");
      out.write("            setTimeout(function() {\n");
      out.write("                notification.remove();\n");
      out.write("            }, 2000);\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
